#!/usr/bin/env python3
# gen_thunks.py — generate the 72 arm64 Java_* entry thunks for the shim from
#   (a) the engine's exported Java_* symbols (readelf), and
#   (b) the DEX-declared native-method shorties (return + param type classes).
# Each thunk has the exact JNI C signature (so the arm64 compiler places args per
# AAPCS64), packs the params into a jvalue[], and forwards to shim_call(), which
# marshals into the guest (soft-float AAPCS32) and runs emulation.
#
#   python3 gen_thunks.py <engine.so> <classes.dex> > src/jni_thunks.gen.c
import sys, struct, subprocess, re

CT={'V':'void','Z':'jboolean','B':'jbyte','C':'jchar','S':'jshort','I':'jint',
    'J':'jlong','F':'jfloat','D':'jdouble','L':'jobject'}
JV={'Z':'z','B':'b','C':'c','S':'s','I':'i','J':'j','F':'f','D':'d','L':'l'}

def engine_exports(so):
    out=subprocess.check_output(["readelf","--dyn-syms","-W",so]).decode()
    names=set()
    for line in out.splitlines():
        m=re.search(r'\b(Java_[A-Za-z0-9_]+)\b', line)
        if m and ' FUNC ' in line and ' UND ' not in line:
            names.add(m.group(1))
    return names

def dex_shorties(path):
    d=open(path,"rb").read()
    u32=lambda o: struct.unpack_from("<I",d,o)[0]
    u16=lambda o: struct.unpack_from("<H",d,o)[0]
    def uleb(o):
        r=0;s=0
        while True:
            b=d[o];o+=1;r|=(b&0x7f)<<s
            if not (b&0x80):break
            s+=7
        return r,o
    string_ids_off=u32(0x3c); type_ids_off=u32(0x44); proto_ids_off=u32(0x4c)
    method_ids_off=u32(0x5c); class_defs_size=u32(0x60); class_defs_off=u32(0x64)
    def string(i):
        o=u32(string_ids_off+i*4); ln,o=uleb(o); return d[o:o+ln].decode('utf-8','replace')
    def typ(i): return string(u32(type_ids_off+i*4))
    def shorty(pi): return string(u32(proto_ids_off+pi*12))
    def method(mi):
        b=method_ids_off+mi*8; return u16(b), u16(b+2), string(u32(b+4))
    res={}
    for i in range(class_defs_size):
        cb=class_defs_off+i*32; cdo=u32(cb+24)
        if not cdo: continue
        o=cdo; sf,o=uleb(o); inf,o=uleb(o); dm,o=uleb(o); vm,o=uleb(o)
        for _ in range(sf): _,o=uleb(o); _,o=uleb(o)
        for _ in range(inf): _,o=uleb(o); _,o=uleb(o)
        for grp in (dm,vm):
            mi=0
            for _ in range(grp):
                diff,o=uleb(o); acc,o=uleb(o); _,o=uleb(o); mi+=diff
                if acc & 0x100:
                    ci,pi,nm=method(mi)
                    cls=typ(ci)[1:-1].replace('/','_')
                    res["Java_%s_%s"%(cls,nm)]=shorty(pi)
    return res

def main():
    so, dex = sys.argv[1], sys.argv[2]
    exports = engine_exports(so)
    shorties = dex_shorties(dex)
    matched=[]; missing=[]
    for name in sorted(exports):
        if name in shorties: matched.append((name, shorties[name]))
        else: missing.append(name)
    P=print
    P("/* jni_thunks.gen.c — GENERATED by gen_thunks.py. Do not edit by hand. */")
    P('#include "jni_entry.h"')
    P("")
    P("/* %d engine exports, %d matched to DEX shorties, %d unmatched */"%(len(exports),len(matched),len(missing)))
    for n in missing: P("/* UNMATCHED (no DEX shorty; emitted as no-arg void): %s */"%n)
    P("")
    for name, sh in matched:
        ret, params = sh[0], sh[1:]
        pdecl = "".join(", %s p%d"%(CT[p],i) for i,p in enumerate(params))
        P("JNIEXPORT %s JNICALL %s(JNIEnv* env, jobject thiz%s){"%(CT[ret], name, pdecl))
        n=len(params)
        P("  jvalue a[%d];"%(n if n else 1))
        for i,p in enumerate(params):
            P("  a[%d].%s = p%d;"%(i, JV[p], i))
        call='shim_call(env, thiz, "%s", "%s", a, %d)'%(name, sh, n)
        if ret=='V':
            P("  %s;"%call)
        else:
            P("  return %s.%s;"%(call, JV[ret]))
        P("}")
    # unmatched -> safe no-arg void stubs (should be rare/none for the engine)
    for name in missing:
        P('JNIEXPORT void JNICALL %s(JNIEnv* env, jobject thiz){ jvalue a[1]; shim_call(env, thiz, "%s", "V", a, 0); }'%(name,name))
    P("")
    P("const shim_thunk_ent SHIM_THUNKS[] = {")
    for name, sh in matched + [(m,"V") for m in missing]:
        P('  { "%s", "%s" },'%(name, sh))
    P("  { 0, 0 }")
    P("};")

if __name__=="__main__": main()
