/* jni_thunks.gen.c — GENERATED by gen_thunks.py. Do not edit by hand. */
#include "jni_entry.h"

/* 72 engine exports, 72 matched to DEX shorties, 0 unmatched */

JNIEXPORT void JNICALL Java_com_rovio_fusion_AlertDialogWrapper_showAlertResultCallback(JNIEnv* env, jobject thiz, jlong p0, jlong p1, jint p2, jint p3){
  jvalue a[4];
  a[0].j = p0;
  a[1].j = p1;
  a[2].i = p2;
  a[3].i = p3;
  shim_call(env, thiz, "Java_com_rovio_fusion_AlertDialogWrapper_showAlertResultCallback", "VJJII", a, 4);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_AudioOutput_nativeMixData(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_fusion_AudioOutput_nativeMixData", "VJLI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_HockeyAppWrapper_setUpBreakpad(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_HockeyAppWrapper_setUpBreakpad", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_LocalNotificationsWrapper_notificationReceived(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_LocalNotificationsWrapper_notificationReceived", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_MyInputHandler_nativeInput(JNIEnv* env, jobject thiz, jint p0, jfloat p1, jfloat p2, jint p3){
  jvalue a[4];
  a[0].i = p0;
  a[1].f = p1;
  a[2].f = p2;
  a[3].i = p3;
  shim_call(env, thiz, "Java_com_rovio_fusion_MyInputHandler_nativeInput", "VIFFI", a, 4);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_MyInputHandler_nativeInputAxis(JNIEnv* env, jobject thiz, jint p0, jfloat p1, jint p2){
  jvalue a[3];
  a[0].i = p0;
  a[1].f = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_fusion_MyInputHandler_nativeInputAxis", "VIFI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_MyInputHandler_nativeKeyInput(JNIEnv* env, jobject thiz, jint p0, jint p1, jint p2, jint p3){
  jvalue a[4];
  a[0].i = p0;
  a[1].i = p1;
  a[2].i = p2;
  a[3].i = p3;
  shim_call(env, thiz, "Java_com_rovio_fusion_MyInputHandler_nativeKeyInput", "VIIII", a, 4);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_MyInputHandler_nativeLoadFromUrl(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_MyInputHandler_nativeLoadFromUrl", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeConfig(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeConfig", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeDeinit(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeDeinit", "V", a, 0);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeFrameClear(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeFrameClear", "V", a, 0);
}
JNIEXPORT jint JNICALL Java_com_rovio_fusion_NativeApplication_nativeGetPossibleOrientations(JNIEnv* env, jobject thiz){
  jvalue a[1];
  return shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeGetPossibleOrientations", "I", a, 0).i;
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeInit(JNIEnv* env, jobject thiz, jint p0, jint p1){
  jvalue a[2];
  a[0].i = p0;
  a[1].i = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeInit", "VII", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeInterruptRender(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeInterruptRender", "V", a, 0);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativePause(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativePause", "V", a, 0);
}
JNIEXPORT jboolean JNICALL Java_com_rovio_fusion_NativeApplication_nativeRender(JNIEnv* env, jobject thiz){
  jvalue a[1];
  return shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeRender", "Z", a, 0).z;
}
JNIEXPORT jboolean JNICALL Java_com_rovio_fusion_NativeApplication_nativeRenderThread(JNIEnv* env, jobject thiz){
  jvalue a[1];
  return shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeRenderThread", "Z", a, 0).z;
}
JNIEXPORT jboolean JNICALL Java_com_rovio_fusion_NativeApplication_nativeResize(JNIEnv* env, jobject thiz, jint p0, jint p1){
  jvalue a[2];
  a[0].i = p0;
  a[1].i = p1;
  return shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeResize", "ZII", a, 2).z;
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_NativeApplication_nativeResume(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeResume", "V", a, 0);
}
JNIEXPORT jboolean JNICALL Java_com_rovio_fusion_NativeApplication_nativeUpdate(JNIEnv* env, jobject thiz){
  jvalue a[1];
  return shim_call(env, thiz, "Java_com_rovio_fusion_NativeApplication_nativeUpdate", "Z", a, 0).z;
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteMessage(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteMessage", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteRegistrationID(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteRegistrationID", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayerBridge_onVideoEnded(JNIEnv* env, jobject thiz, jlong p0, jboolean p1, jint p2, jfloat p3, jfloat p4){
  jvalue a[5];
  a[0].j = p0;
  a[1].z = p1;
  a[2].i = p2;
  a[3].f = p3;
  a[4].f = p4;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayerBridge_onVideoEnded", "VJZIFF", a, 5);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayer_announceOnPause(JNIEnv* env, jobject thiz, jlong p0, jfloat p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].f = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayer_announceOnPause", "VJF", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayer_announceOnResume(JNIEnv* env, jobject thiz, jlong p0, jfloat p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].f = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayer_announceOnResume", "VJF", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayer_onExtraButtonClicked(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayer_onExtraButtonClicked", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayer_onPlay(JNIEnv* env, jobject thiz, jlong p0, jfloat p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].f = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayer_onPlay", "VJF", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_VideoPlayer_onVideoStarted(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_fusion_VideoPlayer_onVideoStarted", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_WebViewWrapper_callNativeFunction(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_fusion_WebViewWrapper_callNativeFunction", "VJL", a, 2);
}
JNIEXPORT jint JNICALL Java_com_rovio_fusion_WebViewWrapper_linkClickedCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  return shim_call(env, thiz, "Java_com_rovio_fusion_WebViewWrapper_linkClickedCallback", "IJL", a, 2).i;
}
JNIEXPORT void JNICALL Java_com_rovio_fusion_WebViewWrapper_urlLoadedCallback(JNIEnv* env, jobject thiz, jlong p0, jboolean p1, jobject p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].z = p1;
  a[2].l = p2;
  shim_call(env, thiz, "Java_com_rovio_fusion_WebViewWrapper_urlLoadedCallback", "VJZL", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_backButtonPressed(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_backButtonPressed", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_checkEmail(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_checkEmail", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_checkPassword(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_checkPassword", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_onButtonClicked(JNIEnv* env, jobject thiz, jlong p0, jint p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].i = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_onButtonClicked", "VJI", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_onRegisterNewAccount(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jobject p2, jint p3, jint p4, jint p5, jobject p6, jint p7){
  jvalue a[8];
  a[0].j = p0;
  a[1].l = p1;
  a[2].l = p2;
  a[3].i = p3;
  a[4].i = p4;
  a[5].i = p5;
  a[6].l = p6;
  a[7].i = p7;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_onRegisterNewAccount", "VJLLIIILI", a, 8);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_onRequestNewPassword(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_onRequestNewPassword", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_IdentityLoginUI_onSignInClicked(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jobject p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].l = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_IdentityLoginUI_onSignInClicked", "VJLL", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_InstallReferrerReceiver_sendReferrer(JNIEnv* env, jobject thiz, jobject p0){
  jvalue a[1];
  a[0].l = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_InstallReferrerReceiver_sendReferrer", "VL", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onAdError(JNIEnv* env, jobject thiz, jlong p0, jint p1, jobject p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].i = p1;
  a[2].l = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onAdError", "VJIL", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onAdHidden(JNIEnv* env, jobject thiz, jlong p0, jboolean p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].z = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onAdHidden", "VJZ", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onAdReady(JNIEnv* env, jobject thiz, jlong p0, jboolean p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].z = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onAdReady", "VJZ", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onAdShown(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onAdShown", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onAdSizeChanged(JNIEnv* env, jobject thiz, jlong p0, jint p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].i = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onAdSizeChanged", "VJII", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_AdsSdk_onClick(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_AdsSdk_onClick", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onCustomControlClicked(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jfloat p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].f = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onCustomControlClicked", "VJLF", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardClick(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardClick", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardReady(JNIEnv* env, jobject thiz, jlong p0, jboolean p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].z = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardReady", "VJZ", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardTrackEvent(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jobject p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].l = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardTrackEvent", "VJLL", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoEnded(JNIEnv* env, jobject thiz, jlong p0, jboolean p1, jfloat p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].z = p1;
  a[2].f = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoEnded", "VJZF", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoTrackEvent(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoTrackEvent", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_linkClickedCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_linkClickedCallback", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_rovioTrackEvent(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jobject p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].l = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_rovioTrackEvent", "VJLL", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_urlLoadedCallback(JNIEnv* env, jobject thiz, jlong p0, jboolean p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].z = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_urlLoadedCallback", "VJZ", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_videoEnded(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jfloat p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].f = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_videoEnded", "VJLF", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_videoStarted(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_videoStarted", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_viewCollapsedCallback(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_viewCollapsedCallback", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_viewExpandedCallback(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_viewExpandedCallback", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_ads_WebViewWrapper_viewHiddenCallback(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_ads_WebViewWrapper_viewHiddenCallback", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_core_Utils_handleReferrerNotSupported(JNIEnv* env, jobject thiz){
  jvalue a[1];
  shim_call(env, thiz, "Java_com_rovio_rcs_core_Utils_handleReferrerNotSupported", "V", a, 0);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_core_Utils_handleReferrerValue(JNIEnv* env, jobject thiz, jobject p0, jlong p1, jlong p2){
  jvalue a[3];
  a[0].l = p0;
  a[1].j = p1;
  a[2].j = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_core_Utils_handleReferrerValue", "VLJJ", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_initFinished(JNIEnv* env, jobject thiz, jlong p0, jboolean p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].z = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_initFinished", "VJZ", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_paymentFinished(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2, jobject p3, jobject p4, jobject p5){
  jvalue a[6];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  a[3].l = p3;
  a[4].l = p4;
  a[5].l = p5;
  shim_call(env, thiz, "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_paymentFinished", "VJLILLL", a, 6);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreDone(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreDone", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreFailed(JNIEnv* env, jobject thiz, jlong p0){
  jvalue a[1];
  a[0].j = p0;
  shim_call(env, thiz, "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreFailed", "VJ", a, 1);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_skuDetailsLoaded(JNIEnv* env, jobject thiz, jlong p0, jobject p1){
  jvalue a[2];
  a[0].j = p0;
  a[1].l = p1;
  shim_call(env, thiz, "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_skuDetailsLoaded", "VJL", a, 2);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetFriendsCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetFriendsCallback", "VJLI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetUserProfileCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetUserProfileCallback", "VJLI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onLoginCompleteCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jboolean p2, jint p3){
  jvalue a[4];
  a[0].j = p0;
  a[1].l = p1;
  a[2].z = p2;
  a[3].i = p3;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onLoginCompleteCallback", "VJLZI", a, 4);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppInviteRequestCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppInviteRequestCallback", "VJLI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppRequestCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppRequestCallback", "VJLI", a, 3);
}
JNIEXPORT void JNICALL Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onShareCallback(JNIEnv* env, jobject thiz, jlong p0, jobject p1, jint p2){
  jvalue a[3];
  a[0].j = p0;
  a[1].l = p1;
  a[2].i = p2;
  shim_call(env, thiz, "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onShareCallback", "VJLI", a, 3);
}

const shim_thunk_ent SHIM_THUNKS[] = {
  { "Java_com_rovio_fusion_AlertDialogWrapper_showAlertResultCallback", "VJJII" },
  { "Java_com_rovio_fusion_AudioOutput_nativeMixData", "VJLI" },
  { "Java_com_rovio_fusion_HockeyAppWrapper_setUpBreakpad", "VL" },
  { "Java_com_rovio_fusion_LocalNotificationsWrapper_notificationReceived", "VL" },
  { "Java_com_rovio_fusion_MyInputHandler_nativeInput", "VIFFI" },
  { "Java_com_rovio_fusion_MyInputHandler_nativeInputAxis", "VIFI" },
  { "Java_com_rovio_fusion_MyInputHandler_nativeKeyInput", "VIIII" },
  { "Java_com_rovio_fusion_MyInputHandler_nativeLoadFromUrl", "VL" },
  { "Java_com_rovio_fusion_NativeApplication_nativeConfig", "VL" },
  { "Java_com_rovio_fusion_NativeApplication_nativeDeinit", "V" },
  { "Java_com_rovio_fusion_NativeApplication_nativeFrameClear", "V" },
  { "Java_com_rovio_fusion_NativeApplication_nativeGetPossibleOrientations", "I" },
  { "Java_com_rovio_fusion_NativeApplication_nativeInit", "VII" },
  { "Java_com_rovio_fusion_NativeApplication_nativeInterruptRender", "V" },
  { "Java_com_rovio_fusion_NativeApplication_nativePause", "V" },
  { "Java_com_rovio_fusion_NativeApplication_nativeRender", "Z" },
  { "Java_com_rovio_fusion_NativeApplication_nativeRenderThread", "Z" },
  { "Java_com_rovio_fusion_NativeApplication_nativeResize", "ZII" },
  { "Java_com_rovio_fusion_NativeApplication_nativeResume", "V" },
  { "Java_com_rovio_fusion_NativeApplication_nativeUpdate", "Z" },
  { "Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteMessage", "VL" },
  { "Java_com_rovio_fusion_RemoteNotificationsClientWrapper_announceRemoteRegistrationID", "VL" },
  { "Java_com_rovio_fusion_VideoPlayerBridge_onVideoEnded", "VJZIFF" },
  { "Java_com_rovio_fusion_VideoPlayer_announceOnPause", "VJF" },
  { "Java_com_rovio_fusion_VideoPlayer_announceOnResume", "VJF" },
  { "Java_com_rovio_fusion_VideoPlayer_onExtraButtonClicked", "VJL" },
  { "Java_com_rovio_fusion_VideoPlayer_onPlay", "VJF" },
  { "Java_com_rovio_fusion_VideoPlayer_onVideoStarted", "VJ" },
  { "Java_com_rovio_fusion_WebViewWrapper_callNativeFunction", "VJL" },
  { "Java_com_rovio_fusion_WebViewWrapper_linkClickedCallback", "IJL" },
  { "Java_com_rovio_fusion_WebViewWrapper_urlLoadedCallback", "VJZL" },
  { "Java_com_rovio_rcs_IdentityLoginUI_backButtonPressed", "VJ" },
  { "Java_com_rovio_rcs_IdentityLoginUI_checkEmail", "VJL" },
  { "Java_com_rovio_rcs_IdentityLoginUI_checkPassword", "VJL" },
  { "Java_com_rovio_rcs_IdentityLoginUI_onButtonClicked", "VJI" },
  { "Java_com_rovio_rcs_IdentityLoginUI_onRegisterNewAccount", "VJLLIIILI" },
  { "Java_com_rovio_rcs_IdentityLoginUI_onRequestNewPassword", "VJL" },
  { "Java_com_rovio_rcs_IdentityLoginUI_onSignInClicked", "VJLL" },
  { "Java_com_rovio_rcs_InstallReferrerReceiver_sendReferrer", "VL" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onAdError", "VJIL" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onAdHidden", "VJZ" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onAdReady", "VJZ" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onAdShown", "VJ" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onAdSizeChanged", "VJII" },
  { "Java_com_rovio_rcs_ads_AdsSdk_onClick", "VJ" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onCustomControlClicked", "VJLF" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardClick", "VJL" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardReady", "VJZ" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onEndCardTrackEvent", "VJLL" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoEnded", "VJZF" },
  { "Java_com_rovio_rcs_ads_VideoPlayerBridge_onVideoTrackEvent", "VJL" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_linkClickedCallback", "VJL" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_rovioTrackEvent", "VJLL" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_urlLoadedCallback", "VJZ" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_videoEnded", "VJLF" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_videoStarted", "VJ" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_viewCollapsedCallback", "VJ" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_viewExpandedCallback", "VJ" },
  { "Java_com_rovio_rcs_ads_WebViewWrapper_viewHiddenCallback", "VJ" },
  { "Java_com_rovio_rcs_core_Utils_handleReferrerNotSupported", "V" },
  { "Java_com_rovio_rcs_core_Utils_handleReferrerValue", "VLJJ" },
  { "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_initFinished", "VJZ" },
  { "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_paymentFinished", "VJLILLL" },
  { "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreDone", "VJ" },
  { "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_restoreFailed", "VJ" },
  { "Java_com_rovio_rcs_payment_google_GooglePlayPaymentProvider_skuDetailsLoaded", "VJL" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetFriendsCallback", "VJLI" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onGetUserProfileCallback", "VJLI" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onLoginCompleteCallback", "VJLZI" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppInviteRequestCallback", "VJLI" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onSendAppRequestCallback", "VJLI" },
  { "Java_com_rovio_rcs_socialnetwork_SocialManagerWrapper_onShareCallback", "VJLI" },
  { 0, 0 }
};
