#!/bin/bash
# emu_interactive_capture.sh — regenerate the INTERACTIVE proofs (PROOF_2/3/4) unattended.
#
# WHY THIS EXISTS
# ---------------
# PROOF_2 (level up and interactive), PROOF_3 (bird launched) and PROOF_4 (in flight) were
# originally produced by keeping emu_interactive.sh's emulator alive and driving it by hand from
# outside (`docker exec ab-emu-run adb shell input ...`). That works, but it means those three
# proofs cannot be regenerated by running a script — so when the shim changed they went stale, and
# when the proxy builds became reproducible they could not be re-anchored with everything else.
# They were left dated 2026-07-26: taken before the allocator fix AND before the proxies were
# reproducible, i.e. against a binary that no longer exists and a heap that was corrupt.
#
# This does the same interaction unattended and captures the three moments, so the interactive
# evidence is reproducible like the rest.
#
#   docker run --rm --network none --device /dev/kvm --group-add 993 \
#       -v "$PWD":/work ab-emu bash /work/port/validation/emu_interactive_capture.sh
set +e
source "$(dirname "$0")/lib_settle.sh"
source "$(dirname "$0")/lib_provenance.sh"
source "$(dirname "$0")/lib_metrics.sh"
( sleep 2100; adb emu kill 2>/dev/null; pkill -9 -f qemu 2>/dev/null ) &
APK=/work/out/angrybirds-8.0.3-x86shim.apk          # diagnostic build, as the originals used
OUT=/work/reports/shots; mkdir -p "$OUT"
LOG="$OUT/interactive_capture.txt"; : >"$LOG"
ABLOG="$OUT/emu_interactive_abshim.txt"; : >"$ABLOG"
say(){ echo "$@" | tee -a "$LOG"; }
FAIL=0
# Delete the PREVIOUS run's captures before doing anything. Without this, a run that dies before the
# capture steps — a failed install was an `exit 0` path until now — leaves three images sitting in
# reports/shots that were never regenerated, next to a log saying DONE. Somebody comparing them
# against a new build would be looking at the old build's screenshots.
rm -f "$OUT/interactive_2.png" "$OUT/interactive_3.png" "$OUT/interactive_4.png"

say "== boot (API 25) =="
emulator -avd abtest -no-window -no-audio -no-boot-anim -no-snapshot -accel on \
         -gpu swiftshader_indirect -partition-size 6144 -wipe-data >/tmp/emu.log 2>&1 &
adb wait-for-device
for i in $(seq 1 150); do [ "$(adb shell getprop sys.boot_completed 2>/dev/null|tr -d '\r')" = 1 ] && break; sleep 2; done
sleep 8
adb shell settings put global airplane_mode_on 1 >/dev/null 2>&1
adb push "$APK" /data/local/tmp/ab.apk >/dev/null 2>&1
INST=fail
for t in 1 2 3 4; do adb shell pm install -r -d /data/local/tmp/ab.apk 2>&1 | grep -q Success && { INST=ok; break; }; sleep 4; done
# exit 1, not the exit 0 this used to be: a run that installed nothing captured nothing, and must
# not report the same status as a run that captured three good frames.
say "install=$INST"; [ "$INST" = ok ] || { say "  [FAIL] install failed — nothing below could be captured"
                                           say "DONE (FAIL=1)"; adb emu kill; exit 1; }
record_build "$APK" "interactive"
adb logcat -c >/dev/null 2>&1; adb logcat -G 32M >/dev/null 2>&1
adb logcat -s abshim > "$ABLOG" 2>/dev/null &
adb shell monkey -p com.rovio.angrybirds -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1

say "== wait for the tutorial card (frame[601]+) =="
for s in $(seq 1 130); do sleep 5
  fn=$(grep -aoE 'frame\[[0-9]+\]' "$ABLOG" 2>/dev/null|tail -1|grep -oE '[0-9]+')
  [ -n "$fn" ] && [ "$fn" -ge 601 ] && { say "  card at ~$((s*5))s frame[$fn]"; break; }
done
sleep 4

# PROOF_2 — tap through the start card; the level is up and interactive.
say "== [PROOF_2] tap start card -> interactive level =="
adb shell input tap 390 266; sleep 4; adb shell input tap 390 266
settle_frames "$ABLOG" 60 180
adb exec-out screencap -p > "$OUT/interactive_2.png" 2>/dev/null
say "  captured interactive_2.png ($(wc -c < "$OUT/interactive_2.png" 2>/dev/null) bytes)"

# PROOF_3 — the slingshot drag releases the bird. Capture SOON after release, while it is still
# clearly a launch rather than an outcome, then again mid-arc for PROOF_4.
say "== [PROOF_3] slingshot drag -> bird launched =="
adb shell input swipe 207 118 110 150 700
sleep 2
adb exec-out screencap -p > "$OUT/interactive_3.png" 2>/dev/null
say "  captured interactive_3.png ($(wc -c < "$OUT/interactive_3.png" 2>/dev/null) bytes)"

say "== [PROOF_4] mid-flight =="
sleep 3
adb exec-out screencap -p > "$OUT/interactive_4.png" 2>/dev/null
say "  captured interactive_4.png ($(wc -c < "$OUT/interactive_4.png" 2>/dev/null) bytes)"

say "== RESULTS =="
PID=$(adb shell pidof com.rovio.angrybirds 2>/dev/null|tr -d '\r')
HF=$(grep -ac 'h_fatal' "$ABLOG" 2>/dev/null); HF=${HF:-0}
say "  h_fatal:     $(h_fatal_report "$ABLOG")"
say "  last frame:  $(grep -aoE 'frame\[[0-9]+\]' "$ABLOG" 2>/dev/null|tail -1)"
say "  final pid:   [${PID:-none}]"
say
# MECHANICAL checks only. Whether interactive_3 caught the bird in flight is a question for a person.
# Whether the file is a picture of anything at all is not — and a run that captured three blank
# rectangles printed DONE and exited 0 exactly like a good one until now.
# NOT read through a pipe: $? would be tee's, the defect that once made a check print [FAIL] and
# exit 0 elsewhere in this suite.
say "== are the captures pictures of anything? =="
python3 "$(dirname "$0")/png_sane.py" --expect 640x320 \
        "$OUT/interactive_2.png" "$OUT/interactive_3.png" "$OUT/interactive_4.png" > /tmp/sane.$$ 2>&1
SANE=$?
while IFS= read -r _l; do say "$_l"; done < /tmp/sane.$$; rm -f /tmp/sane.$$
[ "$SANE" -eq 0 ] || FAIL=$((FAIL+1))
[ -n "$PID" ] && say "  [ OK ] the app was still alive when the captures were taken" \
    || { say "  [FAIL] the app was dead when the captures were taken"; FAIL=$((FAIL+1)); }
[ "$HF" -eq 0 ] && say "  [ OK ] no h_fatal during the capture run" \
    || { say "  [FAIL] h_fatal during the capture run ($HF)"; FAIL=$((FAIL+1)); }
say
say "  STILL NEEDS A HUMAN: these captures are timing-sensitive (a launch, a mid-arc moment)."
say "  Passing here means they are real, non-blank 640x320 frames from a live app — NOT that the"
say "  timing caught the intended instant. Look at them before promoting any to a PROOF_ name."
say "DONE (FAIL=$FAIL)"
adb emu kill >/dev/null 2>&1
exit "$FAIL"
