#!/bin/bash
# emu_interactive_capture.sh — regenerate the INTERACTIVE proofs (PROOF_2/3/4) unattended.
#
# WHY THIS EXISTS
# ---------------
# PROOF_2 (level up and interactive), PROOF_3 (bird launched) and PROOF_4 (in flight) were
# originally produced by keeping emu_interactive.sh's emulator alive and driving it by hand from
# outside (`docker exec ab-emu-run adb shell input ...`). That works, but it means those three
# proofs cannot be regenerated by running a script — so when the shim changed they went stale, and
# when the proxy builds became reproducible they could not be re-anchored with everything else.
# They were left dated 2026-07-26: taken before the allocator fix AND before the proxies were
# reproducible, i.e. against a binary that no longer exists and a heap that was corrupt.
#
# This does the same interaction unattended and captures the three moments, so the interactive
# evidence is reproducible like the rest.
#
#   docker run --rm --network none --device /dev/kvm --group-add 993 \
#       -v "$PWD":/work ab-emu bash /work/port/validation/emu_interactive_capture.sh
set +e
source "$(dirname "$0")/lib_settle.sh"
( sleep 2100; adb emu kill 2>/dev/null; pkill -9 -f qemu 2>/dev/null ) &
APK=/work/out/angrybirds-8.0.3-x86shim.apk          # diagnostic build, as the originals used
OUT=/work/reports/shots; mkdir -p "$OUT"
LOG="$OUT/interactive_capture.txt"; : >"$LOG"
ABLOG="$OUT/emu_interactive_abshim.txt"; : >"$ABLOG"
say(){ echo "$@" | tee -a "$LOG"; }

say "== boot (API 25) =="
emulator -avd abtest -no-window -no-audio -no-boot-anim -no-snapshot -accel on \
         -gpu swiftshader_indirect -partition-size 6144 -wipe-data >/tmp/emu.log 2>&1 &
adb wait-for-device
for i in $(seq 1 150); do [ "$(adb shell getprop sys.boot_completed 2>/dev/null|tr -d '\r')" = 1 ] && break; sleep 2; done
sleep 8
adb shell settings put global airplane_mode_on 1 >/dev/null 2>&1
adb push "$APK" /data/local/tmp/ab.apk >/dev/null 2>&1
INST=fail
for t in 1 2 3 4; do adb shell pm install -r -d /data/local/tmp/ab.apk 2>&1 | grep -q Success && { INST=ok; break; }; sleep 4; done
say "install=$INST"; [ "$INST" = ok ] || { say DONE; adb emu kill; exit 0; }
adb logcat -c >/dev/null 2>&1; adb logcat -G 32M >/dev/null 2>&1
adb logcat -s abshim > "$ABLOG" 2>/dev/null &
adb shell monkey -p com.rovio.angrybirds -c android.intent.category.LAUNCHER 1 >/dev/null 2>&1

say "== wait for the tutorial card (frame[601]+) =="
for s in $(seq 1 130); do sleep 5
  fn=$(grep -aoE 'frame\[[0-9]+\]' "$ABLOG" 2>/dev/null|tail -1|grep -oE '[0-9]+')
  [ -n "$fn" ] && [ "$fn" -ge 601 ] && { say "  card at ~$((s*5))s frame[$fn]"; break; }
done
sleep 4

# PROOF_2 — tap through the start card; the level is up and interactive.
say "== [PROOF_2] tap start card -> interactive level =="
adb shell input tap 390 266; sleep 4; adb shell input tap 390 266
settle_frames "$ABLOG" 60 180
adb exec-out screencap -p > "$OUT/interactive_2.png" 2>/dev/null
say "  captured interactive_2.png ($(wc -c < "$OUT/interactive_2.png" 2>/dev/null) bytes)"

# PROOF_3 — the slingshot drag releases the bird. Capture SOON after release, while it is still
# clearly a launch rather than an outcome, then again mid-arc for PROOF_4.
say "== [PROOF_3] slingshot drag -> bird launched =="
adb shell input swipe 207 118 110 150 700
sleep 2
adb exec-out screencap -p > "$OUT/interactive_3.png" 2>/dev/null
say "  captured interactive_3.png ($(wc -c < "$OUT/interactive_3.png" 2>/dev/null) bytes)"

say "== [PROOF_4] mid-flight =="
sleep 3
adb exec-out screencap -p > "$OUT/interactive_4.png" 2>/dev/null
say "  captured interactive_4.png ($(wc -c < "$OUT/interactive_4.png" 2>/dev/null) bytes)"

say "== RESULTS =="
say "  h_fatal:     $(grep -ac '\[h_fatal\]' "$ABLOG" 2>/dev/null)  (0 = no crash)"
say "  last frame:  $(grep -aoE 'frame\[[0-9]+\]' "$ABLOG" 2>/dev/null|tail -1)"
say "  final pid:   [$(adb shell pidof com.rovio.angrybirds 2>/dev/null|tr -d '\r')]"
say "  NOTE: the three captures are timing-sensitive (a launch and a mid-arc moment). Check the"
say "        images — a blank or results screen means the timing missed, not that the shim failed."
say DONE
adb emu kill >/dev/null 2>&1
