#!/bin/bash
# proof_hashes.sh — (re)generate the integrity section of the screenshot index.
#
# WHY THIS EXISTS
# ---------------
# reports/shots/README.md opens with "Every correctness claim in this repo ultimately rests on these
# images" — and nothing pinned the images. The index recorded what each proof shows, which build made
# it and how to regenerate it, but not what it IS, so a proof could be replaced, truncated or
# corrupted and every check would still pass.
#
# That became concrete rather than theoretical: re-running four capture scripts to backfill
# provenance (R24) regenerated their source screenshots, and PROOF_6 and PROOF_11 no longer md5-match
# the sources the README says they were verified against. Nothing was wrong — a PROOF_ file is an
# archived snapshot and a re-run legitimately produces different pixels — but nothing could show that
# either, because the proofs' own bytes were unrecorded.
#
#   bash port/validation/proof_hashes.sh        # rewrites the section in place
set -e
cd "$(dirname "$0")/../.."
IDX=reports/shots/README.md
MARK='## Integrity — sha256 of every proof'
[ -f "$IDX" ] || { echo "FATAL: $IDX missing"; exit 1; }
ls reports/shots/PROOF_*.png >/dev/null 2>&1 || { echo "FATAL: no PROOF_*.png found"; exit 1; }

TMP=$(mktemp)
awk -v m="$MARK" 'index($0,m){exit} {print}' "$IDX" > "$TMP"
{
  printf '%s\n\n' "$MARK"
  printf 'Generated by `port/validation/proof_hashes.sh`; verified by `verify_claims.sh`. A proof is an\n'
  printf 'ARCHIVED SNAPSHOT — re-running its capture script legitimately produces different pixels, so\n'
  printf 'these hashes pin the evidence itself rather than any relationship to a current working file.\n\n'
  printf '```\n'
  ( cd reports/shots && sha256sum PROOF_*.png )
  printf '```\n'
} >> "$TMP"
mv "$TMP" "$IDX"
echo "  wrote $(ls reports/shots/PROOF_*.png | wc -l) proof hashes into $IDX"
